# Generated by Django 4.1.1 on 2023-01-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField(max_length=100)),
                ('about_us', models.TextField()),
                ('job_location', models.TextField(max_length=100)),
                ('about_job', models.TextField()),
                ('job_responsibilites', models.TextField()),
                ('job_requirement', models.TextField()),
                ('job_preferred', models.TextField()),
            ],
        ),
    ]
